### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by alxzhdanov** [tombh/mc-turtles#3]
Hello 
Always get 

Traceback (most recent call last):
  File "C:\Users\User\mc-turtles\examples\bauble.py", line 2, in <module>
    from turtlecraft import Turtlecraft
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\turtlecraft.py", line 28, in <module>
    from turtlemc import Turtle
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\turtlemc.py", line 6, in <module>
    from cgtypes import vec3, quat
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\deps\cgkit\cgkit\light\cgtypes\__init__.py", line 37, in <module>
    import vec3 as _vec3_module
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\vec3.py", line 99
    raise TypeError, "vec3() takes at most 3 arguments"
                   ^
SyntaxError: invalid syntax
>>> 

How to solve. Thanks a lot

**Comment by tombh** [comment]
Wow, glad you're giving this a go! I suspect your problem is because you're using Python 3. This only runs on Python 2.
